version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directories:
      - "/android"
      - "/android/app"
      - "/android/googlepay"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
