name: Android CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: android
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: android
      run: ./gradlew build

