name: Cocoapods

on:
  push:
    tags-ignore:
      - 'android-*'

permissions:
  contents: read

jobs:
  Deploy:
    name: Publish
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest-stable
      - name: Update Specs Repo
        run: pod repo update
      - name: Lint
        run: |
          pod lib lint
      - name: Push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push
