name: Cocoapods

on:
  push:
    tags:
      - 'ios-*'

jobs:
  Deploy:
    name: Publish
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Update Specs Repo
        run: pod repo update
      - name: Lint
        run: |
          pod lib lint
      - name: Push
        run: |
          pod trunk push
