name: iOS workflow

on:
  push:
    paths:
      - 'ios/**'
      - '.github/**'
      - '**/*.podspec'

jobs:
  Pod-Lint:
    name: Cocoapods Lint
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Update Specs Repo
        run: pod repo update
      - name: Lint
        run: pod lib lint

  Build-Device:
    name: Build Device
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject Entitlements File
        working-directory: ios/Demo/Demo
        run: |
          echo "$IOS_TEST_ENTITLEMENTS_CONTENTS" > DemoDebug.entitlements
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build
        working-directory: ios/Demo
        env:
          scheme: ${{ 'default' }}
        run: |
          scheme="Demo"
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -sdk iphoneos CODE_SIGNING_ALLOWED=NO | xcpretty && exit ${PIPESTATUS[0]}

  Build-Simulator:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-15
    env:
      DEVICE_NAME: "iPhone 16"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject Entitlements File
        working-directory: ios/Demo/Demo
        run: |
          echo "$IOS_TEST_ENTITLEMENTS_CONTENTS" > DemoDebug.entitlements
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Boot simulator
        run: |
          xcrun simctl boot "$DEVICE_NAME" || exit 1
          xcrun simctl bootstatus "$DEVICE_NAME"
      - name: Test
        working-directory: ios/Demo
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          scheme="Demo"
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=$platform,name=$DEVICE_NAME"
